# Generated by Django 5.1.2 on 2024-10-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0003_alter_contactus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
    ]
